### PR TITLE
Render math slightly smaller to match text

### PR DESCRIPTION
**Pull request by DrDrij**

### CODE REVIEW

**Comment by jstac** [comment]
@DrDrij I thought we were going to go the other way --- text slightly large to match maths.

Isn't that what you recommended?

**Comment by jstac** [comment]
@DrDrij I thought we were going to do this the other way --- render text slightly larger to match maths.

Isn't that what you recommended?

**Comment by DrDrij** [comment]
@jstac I went the other way. As changing the default font size would require rewriting a significant part of the whole stylesheet. (All text, branding, nav, header, footer, are based from the default font size). ie. The header looked really chunky even with a 0.1 increase.

**Comment by jstac** [comment]
Doesn't that affect the quality of the maths?  Happy to pay for the extra hours if that's what's required to get it perfect :-)

**Comment by DrDrij** [comment]
@jstac Yes, sorry accidentally merged without review. I'll revert and look into it further.

**Pull request merged**
