### PR TITLE
imports shifted for aiyagari.rst

### PR DESCRIPTION
**Pull request by AnjuJoon**

### CODE REVIEW

**Comment by AnjuJoon** [comment]
@jstac there are some .py files which are dependent on the class created in another py file so they will always break if we will try to run them independently and in some .py files, all the necessary imports are not done because the .py file included in the lecture before that .py file include those imports and it was assumed that this .py file will always be used with that .py file. So should I add imports to .py files so that they do not break if run independently?

**Comment by jstac** [comment]
Thanks @AnjuJoon 

Ah, this is more complex than I thought.

Let's have the following general rules:

* First, let's try to avoid `literalinclude` when we can.  So any py file that's not used in two different lectures should live inside the rst file, like other code.

* For those remaining py files, each one should be able to run individually.  We will have some redundant imports but that's OK.

* Each lecture *after the first 10 lectures* should have the following structure:  The first section is called "Overview".  At the end of this section, we have the following:

```
Let's start with some standard imports:

import numpy as np
import quantecon as qe
import matplotlib.pyplot as plt
%matplotlib inline
```

If those imports make it possible to remove imports below, then great.  But we should make sure that individual py files can execute.

Sorry for the inconsistencies in my instructions.  @AnjuJoon , are you able to implement these changes?

**Comment by AnjuJoon** [comment]
Sure @jstac I will do that for sure.

**Comment by AnjuJoon** [comment]
Hi @jstac this could be merged now!

Also, there are some .py files which are used in more than one lecture and they use the class created in another py file. In this case, even if we add required imports then also the py file will require the class created in another py file. How should I proceed in this case if we want the .py files not to break if run independently.

**Pull request merged**
