### PR TITLE
code moved towards pep8 conventions for amss.rst

### PR DESCRIPTION
**Pull request by AnjuJoon**

### CODE REVIEW

**Comment by mmcky** [comment]
hey @jstac this lecture has timed out on `travis-ci` as well. The code changes don't appear to break any execution.

**Comment by mmcky** [comment]
I will upate the `.travis.yml` to increase the individual lecture time allowed to 30 minutes.

**Comment by mmcky** [comment]
@jstac this is now passing.

**Comment by AnjuJoon** [comment]
Thanks @mmcky :- )

**Pull request merged**
