### PR TITLE
numba_issue5

### PR DESCRIPTION
**Pull request by shlff**
Good afternoon @jstac , I fixed the code-highlighting issue in the plain text by replacing just the single sign `  with the double sign ``.

PS. Once I catch the same issue for the later lectures, I will fix it by following the same strategy.

### CODE REVIEW

**Comment by Harveyt47** [comment]
Hi @shlff , looks all good to me.

**Comment by shlff** [comment]
Thanks a lot, @jstac, @Harveyt47 and @sayaikegawa , I resolved this merge conflict by referencing a [official documentation](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/addressing-merge-conflicts) from GitHub.

**Comment by sayaikegawa** [comment]
I think it looks good

**Comment by jstac** [comment]
Nice job @shlff , well done.

**Pull request merged**
