### PR TITLE
[WIP] Use `jitclass` to optimize `ifp`.

### PR DESCRIPTION
**Pull request by shizejin**
By jitting the `ConsumerProblem` class using `jitclass` and jitting all the other functions that take `ConsumerProblem` as argument, the total running time of the lecture is reduced from 60s to 8s.

The improvement comes from two parts:

1. with `ConsumerProblem` being `jitclass`, we can feed it to the operator directly without using `function_factory` to compile the operator each time we solve the model. Since we are solving 50 models in Exercise 3, the compilation time can be saved is substantial.

2. the structure of `compute_asset_series` is modified. (1) originally we are simulating different Markov sequences of z for each model parameterization separately, but I don't see this necessary. So I only simulate one sequence of z and use it to simulate the asset sequences with different models. As we can see the output figure does not change. (2) I isolate the part in `compute_asset_series` that involves model solving (to be jitted) from the Markov sequence simulating part (cannot be jitted). By dosing so, the first part is accelerated quite a lot because there is a 250000 length loop.

The parallelization of Ex 3 only reduces the running time by 1 second, but makes the code much less concise, so I think we'd better not do that.

Issues to be discussed:

- [ ] `jitclass` does not take functions (even `njit` functions) as fields. But it can take other `jitclass` as fields. Therefore, to make `ConsumerProblem` a `jitclass`, I have to make `LogUtility` a `jitclass` with two methods (`u` and `du`). Moreover, since compiling a `jitclass` requires declaration of field types beforehand, and the numba type of `jitclass` is class-specific, I have to define `LogUtility` first and then `ConsumerProblem`. Also, if I want to move to use `CobbDouglasUtility`, I have to redefine `ConsumerProblem`. This makes the code less general (but general enough if we only focus one utility function family with varying parameters).

- [ ] the second part of the efficiency improvement rests on a jitted `solve_model` function. As format printing is not supported by numba, I could not find a way to print the convergence information in a good manner so I just delete the printing part. But I really don't like this...

### CODE REVIEW

**Comment by jstac** [comment]
Cool, thanks @shizejin !  

I'm excited to look at this.  Let me know when it's ready for a review.

**Comment by shizejin** [comment]
@jstac Hi John, sorry I accidentally press the enter button before writing up the PR summary...

I am now checking the potential inconsistency between the code the lecture content.

Please take a look at the code and let me know what you think, especially about those two issues! Thanks!

**Comment by jstac** [comment]
Wow.  It works.  So cool!

It's a shame we need the constructor function.  I get the impression from [the release notes](http://numba.pydata.org/numba-doc/latest/release-notes.html) that default values in jitclasses are enabled in 0.44, however.  If that's the case, perhaps we should wait until Anaconda updates to 0.44 before we actually replace the code.  What do you think?

Or we could go ahead, and then modify our code once default values are handled.

To simplify the code further, perhaps we should drop the LogUtility class.  Can we store the (jitted) functions `u` and `du` directly in `ConsumerProblem`?

**Comment by jstac** [comment]
Ah, sorry, I'm now reading the above.  I see functions can't be embedded in jitclasses.

Numba is still a bit rough around the edges...

Regarding the printing issue, I guess jitting `solve_model` doesn't save much time, since it's an outer loop.  If not, then let's not jit it, and keep printing.  

It's natural that outer layer calling code and outer loops are not jitted.

**Comment by shizejin** [comment]
@jstac Yeah I think that's a good idea for us to wait until Anaconda is updated.

So far I couldn't find any way to store a function as a field (I should say confidently that this is a unsupported feature). We can make `u` and `du` as methods of `ConsumerProblem`, but this looks strange to me..

`solve_model` needs to be jitted because it is called by `_compute_asset_series` and we want to jit that function, but I think I can dissemble the code into more smaller parts and jit only the time consuming parts if we really want to make `solve_model` to print out the convergence information.

**Comment by jstac** [comment]
Would you mind to keep your eye on Anaconda, to see when Numba updates?  Right now the default version in Anaconda is 0.43.1, so perhaps 0.44 is not far away.

**Comment by shizejin** [comment]
@jstac Sure no problem!

**Comment by shizejin** [comment]
Hi @jstac, it seems that we are about to move to `Numba 0.44` soon, so I modified the code to use default values in `jitclass`. I have tested the use of default values and it is working properly :)

**Comment by jstac** [comment]
Many thanks @shizejin !

I need to take care of some other things this week but I'll review it carefully soon.  

For some of these lectures, we might consider both a plain Python and a jitted implementation, for novice and advanced users respectively.  So please give me a bit of time to consider carefully.

**Comment by shizejin** [comment]
@jstac This plan sounds great! I will wait to move on.

**Comment by jstac** [comment]
Hi @shizejin, I'm going to close this since there are merge conflicts --- and since the code is now a bit old.  If we end up needing some of this code we can just copy and paste it from the closed PR.

**Pull request closed without merging**
