### PR TITLE
[python_advanced_features] remove no-execute tags in rst to allow for generated error output

### PR DESCRIPTION
**Pull request by mmcky**
- [x] remove ``:no-execute:`` tags in RST to allow for generated error output
- [x] remove relevant ``.. code-block:: none`` (@fkazemian, @natashawatkins)

### CODE REVIEW

**Comment by mmcky** [comment]
- [ ] requires ``f = open('us_cities.txt')`` file to run this notebook. Need a way to specify dependency here as we don't want to repeat adding ``us_cities.txt``

**Comment by fkazemian** [comment]
I leave 
screenshot from 2018-10-03 15-13-05
unchanged.

**Comment by mmcky** [comment]
thanks @fkazemian I will need to figure out how best to include raw items like that.

**Comment by mmcky** [comment]
No longer required as ``jupinx`` can skip these blocks through `sphinx-build` flag. 
https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/129

**Pull request closed without merging**
