### PR TITLE
optgrowth_issue

### LINKED ISSUE #937: Optimal growth lecture 1 issue
There is an error occurring in the optimal growth lecture. 
optgrowth
I believe that this error is originating from the ``minimize_scalar`` function in [scipy](https://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html#univariate-function-minimizers-minimize-scalar) which is used in the ``maximize`` function in the optgrowth [lecture](https://python.quantecon.org/optgrowth.html#Scalar-Maximization). 
I also believe that the ``method='bounded'`` variable in the ``minimize_scalar`` function is causing this error. 

When I remove ``method='bounded'`` from being called I get the following output
optgro
This output is obviously not optimal.

### PR DESCRIPTION
**Pull request by Harveyt47**
fix #937

### CODE REVIEW

**Comment by sayaikegawa** [comment]
Thanks @Harveyt47 , that looks good for me.

**Comment by Harveyt47** [comment]
Here are the outputs from the change I have made (on the left) to the unchanged lecture (on the right) on the [website](https://python.quantecon.org/optgrowth.html) which will currently have the bug in #937 as version 1.4.1 of ``scipy`` (current version) has the bug. 

Screenshot from 2020-02-27 11-42-23

Screenshot from 2020-02-27 11-42-32



Screenshot from 2020-02-27 11-42-48

Screenshot from 2020-02-27 11-42-56



Screenshot from 2020-02-27 11-43-05

**Comment by jstac** [comment]
Great PR @Harveyt47.  Please add the ready label when you think it's ready to merge.

**Comment by mmcky** [comment]
hey @Harveyt47 I have just updated our travis specification for testing. Can I merge the latest master into this branch to use this PR as a test case for the `travis` updated?

**Comment by mmcky** [comment]
thanks @Harveyt47 the new travis run shows these all building:

```
Starting notebook execution for website and html conversion(if set in config)...
1569(1/4)  index -- pass -- 1.12s
1570(2/4)  optgrowth -- pass -- 79.15s
1571(3/4)  index_dynamic_programming_grad -- pass -- 1.03s
1572(4/4)  index_dynamic_programming -- pass -- 0.90s
1573build succeeded, 3 warnings.
```

**Pull request merged**
