### PR TITLE
Add contributors to landing

### PR DESCRIPTION
**Pull request by DrDrij**
- Remove bold from compiled date
- Add "View commits" text on new line
- Add "Contributors" link next to "View commits"

image

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @DrDrij !

Two small additional requests: Could you please remove the sentence "The language of instruction is Python", which should be pretty obvious from the title, as well as the sentence after (which starts "This is one of...").

Also, please change "Contributors" to "See all contributors".

**Comment by DrDrij** [comment]
> Two small additional requests: Could you please remove the sentence "The language of instruction is Python", which should be pretty obvious from the title, as well as the sentence after (which starts "This is one of...").
> 
> Also, please change "Contributors" to "See all contributors".

image

**Comment by jstac** [comment]
Perfect.  Thanks @DrDrij.  Please merge when ready @mmcky .

**Comment by mmcky** [comment]
thanks @DrDrij -- once the projects are split -- we will put together a `contributors` page and update the links for the split project.

**Pull request merged**
