### PR TITLE
pandas_panel_issue1

### PR DESCRIPTION
**Pull request by Harveyt47**
Hi @jstac , updating links to this respiratory.

### CODE REVIEW

**Comment by shlff** [comment]
Thanks @sayaikegawa . Hi @jstac , this PR is ready.

**Comment by jstac** [comment]
Thanks all.

@Harveyt47 , can we please review this together tomorrow morning?  Please remind me if I forget.

**Comment by Harveyt47** [comment]
Hi @jstac , yep will do.

**Comment by shlff** [comment]
Good evening, @jstac . As you instructed in the morning, I removed the `html` and `latex` blocks, rephrased the context, updated the 3 links in the code, and made sure they work, see the locations of links to be updated, [1](https://python.quantecon.org/pandas_panel.html#Slicing-and-Reshaping-Data), [2](https://python.quantecon.org/pandas_panel.html#Merging-Dataframes-and-Filling-NaNs), [3](https://python.quantecon.org/pandas_panel.html#Exercise-1) in the webpage.

**Comment by jstac** [comment]
Perfect, thanks @shlff, @Harveyt47 and @sayaikegawa

**Pull request merged**
