### PR TITLE
add coase.rst in main lecture_source_py

### PR DESCRIPTION
**Pull request by AnjuJoon**

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @AnjuJoon -- @jstac I will wait for your review before merging this. Cheers.

**Comment by AnjuJoon** [comment]
@jstac this is the pull request.

**Comment by jstac** [comment]
@AnjuJoon Thanks Anju, much appreciated.  Did you see my email about the need to get the latest from the master branch of the sandpit, where I fixed the red symbols?  Does this PR include that fix?

**Comment by AnjuJoon** [comment]
@jstac  Sorry, I haven't fixed the red symbols yet. I will take the latest version from sandpit in a while and will update you. Also in which index file should I add this lecture?

**Comment by jstac** [comment]
Thanks @AnjuJoon .

Please add it to the "Multi-agent Models" section and in the graduate course but not the undergraduate course.

**Comment by AnjuJoon** [comment]
@jstac I have made the required changes. Please let me know if more changes are needed. Thanks

**Comment by jstac** [comment]
Great work, thanks @AnjuJoon!

**Pull request merged**
