### PR TITLE
scipy_issue7

### PR DESCRIPTION
**Pull request by shlff**
Hello @jstac , I added `x` and `f(x)` labels with our default font size (`fontsize=14`) here.

### CODE REVIEW

**Comment by jstac** [comment]
Hi @shlff , did you check that they are visible?  I thought you would need `ax.legend()`.

**Comment by shlff** [comment]
Hi @jstac , please see the corresponding part in my [notes](https://github.com/shlff/economics_with_python/blob/master/2.4%20scipy.ipynb), where I added labels and legend with font size 14. Do you think it works? I will edit this pull request according to your next comment.

**Comment by shlff** [comment]
Thanks a lot, @jstac . As you instructed, I added the `$` and the legend and set the font size to 12. Thanks for pointing out the missing dollar signs in labels. I will check out all our previous code for the dollar sign issue, and create a new pull request to fix them.

**Comment by jstac** [comment]
Thanks @shlff , this looks better.

**Pull request merged**
