### PR TITLE
numba_issue1

### PR DESCRIPTION
**Pull request by Harveyt47**
Hey @jstac , I have added x and y labels to two graphs in the lecture [numba](https://python.quantecon.org/numba.html#An-Example) and set the font size of the labels to 12.

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @Harveyt47 .

@shlff and @sayaikegawa , could you please add your review?  (You can just say "looks OK" if you think it's fine.)

**Comment by shlff** [comment]
Hi @jstac , it looks good.

**Comment by sayaikegawa** [comment]
Hi @jstac , it looks ok.

**Comment by jstac** [comment]
Thanks @Harveyt47 @shlff and @sayaikegawa, I'll merge now.

**Pull request merged**
