### PR TITLE
jit coleman_policy_iter.rst

### PR DESCRIPTION
**Pull request by natashawatkins**
* moves some code from `optgrowth` into separate files that are also used in this lecture

### CODE REVIEW

**Comment by jstac** [comment]
@natashawatkins Is this ready for review?

**Comment by natashawatkins** [comment]
Almost, but I'm finding that timing 20 iterations for each operator, the Bellman operator is actually faster which seems unusual

**Comment by natashawatkins** [comment]
This is ready to be merged

**Comment by jstac** [comment]
Thanks @natashawatkins , nice work.

**Pull request merged**
