### PR TITLE
lectures moved from sandpit

### PR DESCRIPTION
**Pull request by AnjuJoon**

### CODE REVIEW

**Comment by AnjuJoon** [comment]
@jstac  should I add these lectures in undergrad section or postgrad section?

**Comment by AnjuJoon** [comment]
@jstac everything else looks fine to me. Please let me know if anything escaped from my eyes.

**Comment by jstac** [comment]
Thanks @AnjuJoon.  This looks good.

@mmcky I tried `make website` after `pip install --upgrade sphinxcontrib-jupyter` but no html was created.  

(To check this PR I need to build the whole site.)

Could you please advise?

**Comment by mmcky** [comment]
hey @jstac we haven't released the latest version via `pip` yet for `sphinxcontrib-jupyter`. So it would be best to:

```bash
git clone https://github.com/QuantEcon/sphinxcontrib-jupyter
cd sphinxcontrib-jupyter
python setup.py install
```

**Note:** sequential execution is default (which takes a long time for fresh runs) so I would suggest you use ``make website parallel=True`` which will default to 4 Cores. There are some issues with this on `julia` side but `python` side is robust to running in ``parallel``

**Comment by AnjuJoon** [comment]
@jstac this is ready to merge

**Comment by jstac** [comment]
Thanks all.  I've made some changes to the indices and minor edits.  merging now.

**Pull request merged**
