### PR TITLE
add qe header to notebooks

### PR DESCRIPTION
**Pull request by mmcky**
image

### CODE REVIEW

**Comment by mmcky** [comment]
add in header info from https://github.com/mmcky/quantecon.build.lectures/issues/22

**Comment by mmcky** [comment]
@DrDrij can we remove this header in the `tpl` during `nbconvert`? I won't merge this until we can do that as it will show up on the website and I don't want to have two sets of notebooks :).

**Comment by DrDrij** [comment]
@mmcky Could we use this nbconvert preprocessor to remove the header cell?

`--RegexRemovePreprocessor.patterns="['*qe-menubar-logo*']"
`

https://nbconvert.readthedocs.io/en/latest/api/preprocessors.html#nbconvert.preprocessors.RegexRemovePreprocessor

`jupyter nbconvert --RegexRemovePreprocessor.patterns="['\s*\Z']" mynotebook.ipynb`

**Comment by mmcky** [comment]
thanks @DrDrij I will give that a try today

**Comment by jstac** [comment]
I propose we close this in favor of #196

**Comment by DrDrij** [comment]
@jstac Agreed. I'll further work on making the header a little neater as we go along. I think #196 is a sufficient temporary method for the time being.

**Pull request closed without merging**
