### PR TITLE
FIX DDP lecture (fix #146)

### LINKED ISSUE #146: BUG: Issues with math
- [ ] ``discrete_dp``

image

### PR DESCRIPTION
**Pull request by natashawatkins**
Looks like we just need to unindent for it to work on the site?

### CODE REVIEW

**Comment by mmcky** [comment]
is this surrounded by a non-enumerated list type?

**Comment by natashawatkins** [comment]
What do you mean?

I've unindented it so it's no longer contained in the list. I think we had to do this the other day

**Comment by jstac** [comment]
@AnjuJoon Could you please review this PR?

**Comment by AnjuJoon** [comment]
@jstac yeah sure, I will review this.

**Comment by AnjuJoon** [comment]
@jstac it seems to be corrected by Natasha. I cannot see this problem now in this lecture 
Screenshot from 2019-06-03 09-29-37

**Pull request closed without merging**
