### PR TITLE
linear_model_issue3

### PR DESCRIPTION
**Pull request by sayaikegawa**
Hi @jstac , I removed one of two X_0 in lecture.

### CODE REVIEW

**Comment by shlff** [comment]
Thanks a lot, @sayaikegawa and @jstac . 

Good morning, @jstac , as we discussed, in the subsection [Time Trends](https://python.quantecon.org/linear_models.html#Time-Trends) of lecture ``linear_model``, I calculated ``G = [2a a+b c]``, added ``G`` and kept ``x_0 = [0 0 1] `` (as @sayaikegawa did). 

You can also see the ``ipynb`` file compiled by the ``rst`` file of this subsection with these changes, [here](https://github.com/shlff/economics_with_python/blob/master/linear_model_polynomial.ipynb).

**Comment by jstac** [comment]
Thanks guys, nice PR.  

When I look at the bottom of [this display](https://github.com/shlff/economics_with_python/blob/master/linear_model_polynomial.ipynb), I feel like the last line should change.  Perhaps it should be something like 

"You can now confirm that :math:`y_t = G x_t` has the correct form."

What do you think?

**Comment by shlff** [comment]
Thanks, @jstac . I think it is a good idea.

Given your advice, I kept our previous changes and rephrased the last sentence as you instructed. Please see the new ``ipynb`` file compiled by the ``rst`` file with this new modification, [here](https://github.com/shlff/economics_with_python/blob/master/linear_model_polynomial_v2.ipynb).

**Comment by jstac** [comment]
Thanks @shlff and @sayaikegawa  --- this is a valuable improvement and a nice, clear PR.  Great work.

**Pull request merged**
