### PR TITLE
Update figures for about_py and pandas lectures

### PR DESCRIPTION
**Pull request by duncanhobbs**
This pull request fixes \#692 by updating the StackOverflow figures in pandas.rst. 

I added dplyr, which is popular with R, as a comparison language with SAS and Stata.

This pull request also addresses parts of #705 by updating the 2 StackOverflow figures in about_py.rst.

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @duncanhobbs , I appreciate this.

Actually I don't want to merge it because doing so will close #705, and there are other things in that issue that aren't addressed here.

Just so you know, we try to keep our PRs so that they only address one lecture when possible, which makes it easier to manage them. 

@mmcky Perhaps we need to review our "how to contribute" documentation?  This is the kind of information that we would like to point new RAs to.

@mmcky I can't see the png figures when I build this with jupinx.  Is that what you would expect?

**Comment by mmcky** [comment]
@jstac that is a good idea. I will add that this afternoon. 
Also that isn't what I would expect. If you're on the branch it should build with images. 
I will take a look.

**Comment by mmcky** [comment]
hey @jstac when I run `jupinx -ws --file source/rst/pandas.rst source/rst/t_py.rst` they are coming through for me.

image

when you fetched the downstream fork did you run:

```
git checkout -b duncanhobbs-about-py-figures master
git pull https://github.com/duncanhobbs/lecture-source-py.git about-py-figures
```

**Comment by jstac** [comment]
@mmcky Would you mind to review and merge this when you are happy?

**Comment by mmcky** [comment]
thanks @duncanhobbs. @jstac this looks good to go. I will merge.

**Pull request merged**
