### PR TITLE
edits in additive_functionals.rst

### LINKED ISSUE #903: Additive functionals lecture showing a RuntimeWarning
Search in https://python.quantecon.org/additive_functionals.html

### LINKED ISSUE #917: additive_functionals code uses deprecated numpy.asscalar method
deprecation

Relevant lecture: https://python.quantecon.org/additive_functionals.html

### PR DESCRIPTION
**Pull request by mtiley**
- move plotting functions out of AMF_LSS_VAR
- replace deprecated numpy asscalar with item() to get rid of DeprecationWarning
- avoids RuntimeWarning caused by taking ppf of norm dist with std dev of 0 by setting std dev in those cases to a small value.

Fixes #917, fixes #903

### CODE REVIEW

**Comment by mtiley** [comment]
@jstac @shlff @sayaikegawa @Harveyt47
This PR is looking sad and unreviewed -- is there a better way for me to structure it? Hopefully this comment will make things clearer. 

- the main lines of interest in my opinion are 507-520 (my proposed solution to the RuntimeWarning). I am keen to hear your thoughts on this.

Below are screenshots of the output (before my changes on left, after on right). I set the numpy seed so that random variation would be removed -- they should be identical (and are, as far as I can tell.)

1bef1aft

2bef2aft

3bef3aft

4bef4aft

5bef5aft

**Comment by jstac** [comment]
Thanks @mtiley .  I'll wait until at least one of @sayaikegawa @shlff and @Harveyt47 review.  Once someone has reviewed and feedback has been incorporated, please add the "ready" label and then I'll take a look.

**Comment by jstac** [comment]
Thanks @shlff , I agree.

@mtiley , would you mind to make those plots a better shape?  Perhaps a bit shorter vertically?

**Comment by jstac** [comment]
Thanks @mtiley and @shlff --- this was a lot of work.  The PR was very nicely done.

I might make some small tweaks later but for now I'm going to merge.

**Pull request merged**
