### PR TITLE
add cass-koopmans lecture

### PR DESCRIPTION
**Pull request by natashawatkins**
Things to do:
* Check list indentation
* Remove rogue `\`s that are removing spaces
* Clean up code
* Check headers
* Fix equations
* Add in proper equation referencing and check against original lecture
* Add to toctree

### CODE REVIEW

**Comment by jstac** [comment]
Please keep an eye out for systematic problems with the conversion process.  We can flag them as issues with pandoc, since their ipynb handling is new: https://github.com/jupyter/nbconvert/issues/950.

If there are issues that affect us I'm very happy to support work on putting in fixes (CC @AakashGC @mmcky @DrDrij).

**Comment by natashawatkins** [comment]
I spoke to Brandon and I think he switched a few settings over in the script to deal with some of the above issues, not sure how it turns out yet though

It would be nice to automate this process at least partially

**Comment by fkazemian** [comment]
- [ ] .

**Comment by fkazemian** [comment]
- [ ] .

**Comment by fkazemian** [comment]
- [ ] .

**Comment by fkazemian** [comment]
- [ ] .

**Comment by fkazemian** [comment]
- [ ] checking space. For example:

**Comment by fkazemian** [comment]
- [ ] .

**Comment by fkazemian** [comment]
- [ ] .

**Comment by fkazemian** [comment]
- [ ] .

**Comment by fkazemian** [comment]
- [ ] indexing problems. For example:

**Comment by fkazemian** [comment]
- [ ] I think the second one( in this PR ) is correct, right?

**Comment by natashawatkins** [comment]
thanks @fkazemian, I've added comments/feedback to yours

**Comment by fkazemian** [comment]
Hi @natashawatkins 

in these two equations: 
first : 


second: 
screen shot 2019-02-27 at 1 45 31 pm
screen shot 2019-02-27 at 1 45 16 pm

are using different approch to writing their code: first is based on using different ` math` blocks for each equation and different label in each blocks and the second one is using` \begin{align}  \end{align} `blocks. I want make them equal, which one is prefered? (If I fix this then I can fix their refrences and all the refrences is fixed. )

**Comment by fkazemian** [comment]
Hi @natashawatkins 
is this correct? I think maybe T+1 is index. 
screen shot 2019-02-26 at 6 20 37 pm

**Comment by fkazemian** [comment]
screen shot 2019-02-26 at 6 20 03 pm

editional `)`

solved: https://github.com/QuantEcon/lecture-source-py/pull/202/commits/d15840e5fd34730054eac2c079170a7891d7f986
screen shot 2019-02-27 at 1 56 36 pm

**Comment by fkazemian** [comment]
Hi @natashawatkins , Would you please check these commit 
https://github.com/QuantEcon/lecture-source-py/pull/202/commits/360212c8d79676dad09ac44580ab1160384aaef4
because it's fixing some typos and maybe I was wrong.

**Comment by natashawatkins** [comment]
Thanks @fkazemian, I corrected one more typo. You're right, the subscript should be T+1, I fixed this too.

**Comment by fkazemian** [comment]
Hi @natashawatkins I just fixed the references and checked it.

**Comment by natashawatkins** [comment]
thanks @fkazemian this looks good to me!

I've just updated the plotting code - only one remaining issue with the 6 subplots varying T, having Brandon look at it

**Comment by jstac** [comment]
Thanks @fkazemian @natashawatkins .  If there are systematic issues with the build system or the conversion to rst, please inform @DrDrij

**Comment by jstac** [comment]
@natashawatkins @fkazemian Can you please update me on this PR?  What still needs to be fixed?

**Comment by natashawatkins** [comment]
2 of the plots look a bit strange, the last one and the 6 panel one. Brandon said he would have a look at it this week. Also I asked @fkazemian if she could check -- it's probably using the wrong variable/wrong indexing somewhere.

**Comment by natashawatkins** [comment]
Fixed these issues - should be ready to merge

**Comment by natashawatkins** [comment]
image

How is this @jstac? It looked better to have the bottom two align, but the top one was clashing with the equation number

**Comment by jstac** [comment]
@natashawatkins Nice work, thanks!

I'm merging this into master and then @thomassargent30 is going to tidy up.  Please don't make the master branch live until then (CC @mmcky).

**Pull request merged**
