### PR TITLE
correction for missing word in pdf

### LINKED ISSUE #687: Text Such as "\alpha" in latex is ignored while building pdf due to "\"
The text such as \alpha and \beta (not in math environment) is not reflected in pdf because it is starting with a "\". For example the highlited line in both the below figures

Screenshot 2019-09-20 at 11 56 15 PM
Screenshot 2019-09-20 at 11 56 46 PM

### PR DESCRIPTION
**Pull request by AnjuJoon**
fixes #687

### CODE REVIEW

**Comment by AnjuJoon** [comment]
Hi @jstac, if you could spare some time then, please review this PR.

**Comment by jstac** [comment]
Thanks @AnjuJoon.  Have you tested this for notebooks/web/pdf?

**Comment by AnjuJoon** [comment]
Hi @jstac Yes it is tested and is working fine in pdf notebooks and web!

**Comment by jstac** [comment]
Thanks @AnjuJoon , I appreciate your careful work.

**Pull request merged**
