### PR TITLE
fix [mle] warnings and errors

### PR DESCRIPTION
**Pull request by fkazemian**
#28

### CODE REVIEW

**Comment by fkazemian** [comment]
Hi @natashawatkins , would you please tell me which block has a warning?

**Comment by natashawatkins** [comment]
Following 'we'll use robust standard errors'

**Comment by fkazemian** [comment]
when I'm running it locally, the jupyter file and its html is fine and I don't get any warnings:

screenshot from 2018-10-04 15-06-24

screenshot from 2018-10-04 15-06-17

**Comment by natashawatkins** [comment]
What  version of statsmodels do you have?

image

**Comment by natashawatkins** [comment]
@fkazemian could you try updating and rerunning this, because I don't believe I was getting the same output results

**Comment by natashawatkins** [comment]
This was already done in #60 by the way

**Comment by jstac** [comment]
@AnjuJoon Could you please review this PR?

**Comment by AnjuJoon** [comment]
@jstac sure, I will review this.

**Comment by jstac** [comment]
@AnjuJoon If I remember correctly, you said that this pull request can be closed?  Is that right?

Thanks for all your help.

**Comment by AnjuJoon** [comment]
@jstac yes we can close this PR. I have made a pull request regarding this lecture but not related to this issue. This issue is not anymore in the lecture. Thanks!

**Pull request closed without merging**
