### PR TITLE
Add complex_and_trig.rst

### PR DESCRIPTION
**Pull request by natashawatkins**
The initial commit is a result of running the latex script here (https://github.com/QuantEcon/ipynb_to_rst_tools) and then converting with nbconvert.

The second commit adds manual edits needed.

TODO: Add to toctree

### CODE REVIEW

**Comment by jstac** [comment]
Hi @natashawatkins , @thomassargent30  recommended using pandoc >= 2.6 for the conversion.  I imagine it's more efficient if we unify around a single conversion tool and improve it / get better at using it.  Thoughts?

**Comment by natashawatkins** [comment]
I was trying to use that but I was getting an error - `Reader unknown: ipynb` or something. I've sent a message to Brandon about it.

**Comment by jstac** [comment]
You might need to update pandoc.  It's only just started supporting ipynb natively.

**Comment by natashawatkins** [comment]
I deleted my installation and installed the latest version from here: https://github.com/jgm/pandoc/releases/tag/2.7

and was still having issues

**Comment by natashawatkins** [comment]
Fixed this - there was an anaconda version overriding

**Comment by natashawatkins** [comment]
Ok I've added a note about the anaconda version here: https://github.com/QuantEcon/ipynb_to_rst_tools/blob/master/README.md

**Comment by jstac** [comment]
Thanks @natashawatkins , nice work.

**Comment by natashawatkins** [comment]
@jstac I've added the latest from the sandpit. I added this to the tools and techniques section following linear algebra -- what do you think? Also this is high school level, should I also add this to the undergrad section?

**Pull request merged**
