### PR TITLE
replace` literal-include` with the actual code in a `code-block::python3` 

### PR DESCRIPTION
**Pull request by fkazemian**
replace` literal-include` with the actual code in a `code-block::python3` in the case where the file isn't used somewhere else

****Python****

- [x] - py_source/about_py.rst
- [x] - py_source/additive_functionals.rst
- [x] - py_source/aiyagari.rst
- [x] - py_source/amss.rst
- [x] - py_source/amss2.rst
- [x] - py_source/amss3.rst
- [x] - py_source/arellano.rst
- [x] - py_source/arma.rst
- [x] - py_source/calvo.rst
- [x] - py_source/career.rst
- [x] - py_source/chang_credible.rst
- [x] - py_source/chang_ramsey.rst
- [x] - py_source/classical_filtering.rst
- [x] - py_source/coleman_policy_iter.rst
- [x] - py_source/debugging.rst
- [x] - py_source/discrete_dp.rst
- [x] - py_source/dyn_stack.rst
- [x] - py_source/egm_policy_iter.rst
- [x] - py_source/estspec.rst
- [x] - py_source/finite_markov.rst
- [x] - py_source/getting_started.rst
- [x] - py_source/harrison_kreps.rst
- [x] - py_source/hist_dep_policies.rst
- [x] - py_source/ifp.rst
- [x] - py_source/jv.rst
- [x] - py_source/kalman.rst
- [x] - py_source/lake_model.rst
- [x] - py_source/linear_algebra.rst
- [x] - py_source/linear_models.rst
- [x] - py_source/lln_clt.rst
- [x] - py_source/lqcontrol.rst
- [x] - py_source/lqramsey.rst
- [x] - py_source/lu_tricks.rst
- [x] - py_source/lucas_model.rst
- [x] - py_source/markov_asset.rst
- [x] - py_source/markov_perf.rst
- [x] - py_source/matplotlib.rst
- [x] - py_source/matsuyama.rst
- [x] - py_source/mccall_model.rst
- [x] - py_source/mccall_model_with_separation.rst
- [x] - py_source/mle.rst
- [x] - py_source/multiplicative_functionals.rst
- [x] - py_source/numba.rst
- [x] - py_source/numpy.rst
- [x] - py_source/odu.rst
- [x] - py_source/ols.rst
- [x] - py_source/oop_intro.rst
- [x] - py_source/opt_tax_recur.rst
- [x] - py_source/optgrowth.rst
- [x] - py_source/orth_proj.rst
- [x] - py_source/pandas.rst
- [x] - py_source/pandas_panel.rst
- [x] - py_source/perm_income.rst
- [x] - py_source/perm_income_cons.rst
- [x] - py_source/python_advanced_features.rst
- [x] - py_source/python_by_example.rst
- [x] - py_source/python_essentials.rst
- [x] - py_source/python_oop.rst
- [x] - py_source/rational_expectations.rst
- [x] - py_source/rob_markov_perf.rst
- [x] - py_source/robustness.rst
- [x] - py_source/samuelson.rst
- [x] - py_source/schelling.rst
- [x] - py_source/sci_libs.rst
- [x] - py_source/scipy.rst
- [x] - py_source/short_path.rst
- [x] - py_source/smoothing.rst
- [x] - py_source/stationary_densities.rst
- [x] - py_source/uncertainty_traps.rst
- [x] - py_source/wald_friedman.rst
- [x] - py_source/writing_good_code.rst

### CODE REVIEW

**Comment by mmcky** [comment]
@natashawatkins some of these are VERY long. Do we definitely want all code in the RST?

**Comment by natashawatkins** [comment]
I think this should have been done in separate PRs... I'm worried because I've made substantial edits in other PRs and I don't want them to cause merge conflicts...

**Comment by mmcky** [comment]
I agree. let's leave this to the end and put it on hold for now.

**Comment by natashawatkins** [comment]
This has been generally done across the lectures. Will close now.

**Pull request closed without merging**
