### PR TITLE
FIX: add note admonition for numba version issue

### PR DESCRIPTION
**Pull request by mmcky**
This PR updates `optgrowth` and `coleman_policy_iter` with a note to update `numba=0.44.1` to fix the `nopython` mode issue in `quantecon`. 

**before merging** we need to check:

- [ ] update to `numba=0.44.1` on build server fixes coverage issues (running now)
- [x] `note` construct works with `sphinxcontrib-jupyter` and our `html` template
- [x] remove `note` once `anaconda` is updated (https://github.com/QuantEcon/quantecon.build.lectures/issues/124). Tracking issue setup.

### CODE REVIEW

**Comment by mmcky** [comment]
image

The embedded `code-block` doesn't work but we could inline the instruction to install via `conda`. 
@jstac are you happy with the note look and feel?

**Comment by mmcky** [comment]
here is the inline version

image

**Comment by mmcky** [comment]
- [x] I also confirm the upgrade in `numba` does fix the issue with the lectures.

**Comment by jstac** [comment]
Perfect.  Thanks @mmcky , good plan and nice job.

**Pull request merged**
