### PR TITLE
remove_names

### LINKED ISSUE #958: Sanitize lectures of co-author / co-contributor statements
> remove all co-author statements --- has to be done carefully because the wording varies so it's hard to search.

As part of the transfer to new license we need to check all `rst` files and remove `co-author` statements. Presentations are varied so will require going through the first ~10% of each lecture `rst` file looking for statements like:

`pandas_panel.rst` contains `Most of this lecture was created by Natasha Watkins`

This will resolve item 2 in #946

### PR DESCRIPTION
**Pull request by sayaikegawa**
Hi @jstac and @mmcky , I removed all names.

fix #958

### CODE REVIEW

**Comment by jstac** [comment]
Nice job @sayaikegawa.  It looks good.  Did you make a list of the names?

@mmcky , I'll leave it for you to handle the merge.

**Comment by sayaikegawa** [comment]
Hi @jstac , I'll send you the list after I add names in credits page to my list.

**Comment by jstac** [comment]
Thanks @sayaikegawa .  I suggest that you post them here: https://github.com/QuantEcon/lecture-source-py/issues/946

**Comment by mmcky** [comment]
thanks @sayaikegawa -- more than I thought. 

I might merge this now to prevent merge conflicts `:-)`

**Pull request merged**
