### PR TITLE
imports shifted from uncertainty_traps.py

### PR DESCRIPTION
**Pull request by AnjuJoon**

### CODE REVIEW

**Comment by jstac** [comment]
@AnjuJoon @mmcky 

I have a concern about these changes: The stand alone Python files (the *.py files) are being stripped of their imports, which means that they no longer execute correctly unless embedded in the correct notebook.  

After yesterday, the file `amflss.py` already has this property.

I don't like to have broken *.py files in our repo.

I suggest that we take the approach of embedded all the code in the lectures, and dropping the `literalinclude`s.

Then, imports are shifted to the top, like in this PR, and *.py files are deleted.

The only issue is that some *.py files might be used by two separate lectures, which means that if we eliminate all *.py files we end up with repetition.  @AnjuJoon , will this be an issue for any lectures?  Could you please investigate?

Let me know if something isn't clear.

**Comment by AnjuJoon** [comment]
@jstac, yeah I agree with you that it will leave the *.py files broken which is not a good idea, but I will not completely support repetition as well since there are many *.py files which are used in more than 1 lecture. 

I think there is a tradeoff, we have to compromise at some place.

**Comment by jstac** [comment]
Hi @AnjuJoon , how many py files are used in multiple lectures, do you know?

How are they supported?  Each lecture refers to py files in their own folder in `lecture_specific`.  So if a py file is used multiple times, is it copied to multiple folders?

**Comment by AnjuJoon** [comment]
Hi @jstac I was counting the number of files repeated, it's approximately 8-9 *py files which are used in more than 1 lecture. Also, those py files are not copied to multiple folders. .py file in the folder of one of the lecture is used by the reference of that lecture folder in other lectures. For example-

amlss_scalar.py is in multiplicative_functionals folder and is used in additive_functionals as:
.. literalinclude:: /_static/lecture_specific/multiplicative_functionals/amflss_scalar.py

**Comment by jstac** [comment]
Thanks @AnjuJoon , that's helpful.

Let's proceed as follows: Near the top of each lecture, just as you have done, we'll start with 

```
Let's start with following imports:
￼￼
￼ .. code-block:: ipython
￼
￼     import matplotlib.pyplot as plt
￼     %matplotlib inline
￼     import numpy as np
```

and whatever additional imports are required.  So, in this respect, our plan does not change.  For example, I will accept this PR once you acknowledge.

However, in each *.py file, please add the minimum number of imports to allow the code to run.  (In come cases, just `import numpy as np` will be enough.)

Note that `amflss.py` needs to be fixed.

**Comment by AnjuJoon** [comment]
Hi @jstac, Sure I would do that. This PR could be merged now then. Thanks!

**Pull request merged**
