### PR TITLE
FIX: Table Formatting -- allow non-generic tables

### PR DESCRIPTION
**Pull request by mmcky**
working with @drdrij on a fix for theme support for non-generic tables by adding an ``html`` only block ahead of tables. 

See Issue #30

### CODE REVIEW

**Comment by mmcky** [comment]
@DrDrij adjustments have now been made to `jupinx`

**Comment by DrDrij** [comment]
@mmcky This is now working well. Good to go 👍

**Comment by mmcky** [comment]
@jstac I have updated this branch from master and checked it still works well. It will improve the look of the parameters table in `harrison_kreps` and can be merged when you're ready.

**Comment by jstac** [comment]
Great, thanks @mmcky

**Pull request merged**
