### PR TITLE
additive_functionals: replaced deprecated np.asscalar(a) with a.item()

### LINKED ISSUE #917: additive_functionals code uses deprecated numpy.asscalar method
deprecation

Relevant lecture: https://python.quantecon.org/additive_functionals.html

### PR DESCRIPTION
**Pull request by mtiley**
- also minor grammatical edits
Fixes #917

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @mtiley 

Could one of you please review this @sayaikegawa @Harveyt47 @shlff ?

**Comment by mtiley** [comment]
Thanks @shlff. The `RuntimeWarning` was already present before I made any changes (see #903). 

I thought it would be best to solve the `DeprecationWarning` in a separate PR and as a separate issue while working on the `RuntimeWarning`, as the two are not related.

**Comment by Harveyt47** [comment]
Hi @mtiley , you've fixed the issue of ``DeprecationWarning`` on my end. Cheers.

**Comment by shlff** [comment]
Thanks @mtiley and @jstac , nice job to solve issue #917 . The code looks nice. Let's solve issue #903 in another PR.

**Pull request closed without merging**
