### PR TITLE
unicode characters in getting_started.rst

### PR DESCRIPTION
**Pull request by AnjuJoon**

### CODE REVIEW

**Comment by AnjuJoon** [comment]
@jstac the unicode characters are written in math environment in all the lectures except this one. These unicode characters are missing in pdf in this lecture. If we want to use unicode characters without math environment then we need to use the \setmainfont{CMU Serif} in tex files.

**Comment by mmcky** [comment]
@AnjuJoon is this an issue with the interpreted role. It might be because the unicode is wrapped as an inline code block using:
```
`<unicode>`
```
Does it work if you use:
```
 :math: `<unicode>`
```
i.e. should you just be prepending the `:math:`

**Comment by AnjuJoon** [comment]
@mmcky in latex for our present template if unicode character is wrapped in math environment or it is written as \(\alpha)\  then it works fine but if it is only `α` then we need to use  \setmainfont{CMU Serif} to make it okay for tex file to consider unicode characters like that. I was trying to add this CMU Serif to tex template but failed to do so due to some compatibility issues with the template. 
I will add this to the template as soon as I will get some time.

**Comment by jstac** [comment]
This is a good solution @AnjuJoon .  Thanks.

**Pull request merged**
