### PR TITLE
Equal math font size

### PR DESCRIPTION
**Pull request by DrDrij**
- Set `base` font size of 17px (equal across all browsers)
- Set body font and all elements relative to this `base` font size
- Fix issue where math would break out of container on mobile (you can now scroll horizontally on wide equations)
- Tidy CSS formatting

**Outcome:** inline math and text now match size more closely (body default font size is now larger to match the MathJax rendered inline math).

### CODE REVIEW

**Review by jstac — APPROVED** [review]

**Comment by DrDrij** [comment]
See top window - default font size slightly increased to match math. This also improves readability.
Going the other way wasn't achievable because certain equations would corrupt at any smaller rendering size.

image

**Comment by jstac** [comment]
Perfect.  I agree it improves readability.  It forces us to be concise, which is good.

**Comment by jstac** [comment]
@mmcky, I'll leave this to you to merge.

**Comment by mmcky** [comment]
thanks @DrDrij can I ask is the `css` currently unified for `lecture-python-programming` ... `lecture-python-advanced` sites? 

If not can you make a PR for each of the other repos as well?

**Comment by DrDrij** [comment]
@mmcky Done!

**Pull request merged**
