### PR TITLE
add pip install to lectures

### PR DESCRIPTION
**Pull request by natashawatkins**
* Need to run on testing server

### CODE REVIEW

**Comment by natashawatkins** [comment]
@mmcky are you able to run these change on the testing server? Ideally without any packages other than Anaconda installed? Thanks

**Comment by mmcky** [comment]
the results of this branch is what is currently on preview-lectures.quantecon.org - but I think output should be suppressed for these cells.

**Comment by jstac** [comment]
@mmcky I find it a bit hard to use the preview site because when I click on a particular lecture, it takes me to the live site.

We discussed this before but I can't remember what current status of the issue is.  Can you please update me?

I agree that output of the pip install commands should be suppressed.   @natashawatkins would you mind to implement?

Thanks for putting this PR together.

**Comment by natashawatkins** [comment]
Added all the `no-output` flags

**Comment by natashawatkins** [comment]
@mmcky I'd like to test these on the server without any packages apart from anaconda though, just to check I've added all the right pip installs -- is this possible?

**Comment by mmcky** [comment]
@jstac the reason it is setup like it is re: preview site is so that the downloadable notebooks are built using html references (rather than relative references) so they link to something. The solution will be to build a separate set of download notebooks to the notebooks used in building the html. 

@natashawatkins not going to reset the environment on the build system. However that sort of testing will be possible when we migrate to using docker. The only thing installed on the build system other than anaconda will be `quantecon` and `sphinxcontrib-jupyter` and `sphinxcontrib-bibtex` and `pybtex=0.29`

**Comment by jstac** [comment]
@mmcky Do you agree that this makes the preview site significantly less useful?   If not, please let me know how you operate.  If so, would you mind to open an issue on this topic, so we can discuss?  I'm happy with any suggestions that improve our workflow and our ability to review the site.

**Comment by mmcky** [comment]
@jstac absolutely it does. it was only ever a short term solution -- trying to avoid `3` or `4` sets of notebooks.

**Comment by mmcky** [comment]
@natashawatkins sorry I gave you the wrong info. Instead of `no-output` it should be `hide-output` for the class type. Would you have time to swap those out with a `grep`?

**Comment by jstac** [comment]
@mmcky Roger that.  Please open an issue tracking this problem if there isn't one.

**Comment by natashawatkins** [comment]
Done!

**Comment by mmcky** [comment]
thanks @natashawatkins. Just started a new build.

**Comment by jstac** [comment]
@mmcky @natashawatkins 

I just realized we haven't merged this, so we'll need to do so before we can properly test colab.  I sure wish I had someone who would take care of this process for me and see it through.    

@mmcky Are you happy to have this merged?  After that we need to build again, and then check colab.  Do you want me to do that?

**Comment by jstac** [comment]
@natashawatkins points out that the version on the preview site is based on this branch.  she is now testing.

@mmcky, did you open the issue that I requested above?

**Comment by natashawatkins** [comment]
This should be ready to merge — I’ll fix any errors that come up in testing.

**Comment by mmcky** [comment]
issue added: https://github.com/QuantEcon/quantecon.build.lectures/issues/95. 

Merging this now.

**Pull request merged**
