### PR TITLE
Shift imports

### PR DESCRIPTION
**Pull request by AnjuJoon**

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @AnjuJoon .  Could you please fix the merge conflict?

**Comment by AnjuJoon** [comment]
Hi @jstac, I do not know why but resolve conflicts button is not active for me. I am attaching the screenshot here 
Screenshot 2019-08-16 at 1 42 33 PM

**Comment by jstac** [comment]
@AnjuJoon It's not active for me either.  I'm not sure why.  Unfortunately you'll need to close this PR and make a new one.

**Comment by mmcky** [comment]
hey @AnjuJoon it is usually greyed out when the conflict is more complex than simple issues that can be resolved via GitHub. It will need to be resolved by merging `master` into the branch and managing the merge through the command line.

**Comment by AnjuJoon** [comment]
Thanks @mmcky that was very helpful!

**Pull request closed without merging**
