### PR TITLE
Shift code

### PR DESCRIPTION
**Pull request by AnjuJoon**

### CODE REVIEW

**Comment by AnjuJoon** [comment]
@jstac there are some .py files which are not used at all. What to do with those .py files?

**Comment by jstac** [comment]
@AnjuJoon This PR is actually quite confusing for me.  I can't keep track of what's happening.

For example, here I see you are dealing with the aiyagari lecture, but there's also another PR related to the same lecture.

What I would like is one PR per lecture.  That PR only deals with fixing one lecture, and it makes all the steps for that lecture together.

**Comment by jstac** [comment]
Regarding the py files that aren't used, please delete them.

**Comment by AnjuJoon** [comment]
> @AnjuJoon This PR is actually quite confusing for me. I can't keep track of what's happening.
> 
> For example, here I see you are dealing with the aiyagari lecture, but there's also another PR related to the same lecture.
> 
> What I would like is one PR per lecture. That PR only deals with fixing one lecture, and it makes all the steps for that lecture together.

@jstac Please merge this PR and I am making a separate PR for each lecture after this PR. The other PR related to aiyagari lecture, can we just leave that alone for some time? I will close that PR once this will be merged or maybe I could just resolve conflicts in that PR if in case the merge conflicts will not be serious. 

> Regarding the py files that aren't used, please delete them.

Sure!

**Comment by jstac** [comment]
@AnjuJoon I don't really like merging PRs that I find confusing but in this case I'll trust your judgement and merge.  Afterwards I'll delete the branch.

**Pull request merged**
