### PR TITLE
FEAT: Make commands for better user experience

### PR DESCRIPTION
**Pull request by AakashGfude**
Make command structure in this PR :- 

`make setup` - installs the dependencies

`make jupyter` - converts rst to ipynb (unexecuted)

`make website` - converts rst to website (along with execution and conversion to html)

`make website parallel=True` - parallel version of make website

`make preview` - opens the unexecuted notebook folder (_build/jupyter)

`make preview lecture=code_blocks` - opens the unexecuted lecture (code_blocks.ipynb in this case)

`make preview target=website` -creates a python server and serves the `_build/jupyter_html` folder 

There is an extra `make local` command here, which has not been tampered with at present. Should I change it to something like `make website env=local` or something?

### CODE REVIEW

**Comment by jstac** [comment]
Perfect, thanks!

**Comment by jstac** [comment]
Sorry, I missed the question.  `make local` is used as far as I know by people writing content (like me) who want to see changes to local figures.  If so, perhaps it should be applied to `make jupyter`.  

In fact, now I think about it more carefully, `make jupyter` should be focused on local viewing.  So this behaviour should be default in `make jupyter`.  

Is the local specialization also necessary for `make website`?  That I don't know about so I don't have an opinion.  But if it is, then adding `env=local` sounds like a good approach.

**Comment by AakashGfude** [comment]
@jstac  , I am not sure if its necessary for `make website`. Earlier we had the whole pipeline till the website phase, built into `make jupyter`, so I could not figure out from the command, till which stage of the pipeline is it necessary.

**Comment by jstac** [comment]
Great, thanks @AakashGfude.  Let's omit it from `make website`.

The rule for the UX will be, let's keep it as minimal as possible, and only add later on if we're convinced we need something else.

@mmcky Please comment or sign off on this when you're ready.

**Comment by jstac** [comment]
@jlperla @arnavs 
We're standardizing the make commands for the build system.  These changes are for `lecture-source-py` but we'll propogate them out to `-jl` too.

Please see the list of make commands above.  Is there anything else you need?  Please remember that we want to keep it minimal and uncluttered.   I'll merge in a day or so if you don't have comments.

**Comment by mmcky** [comment]
thanks @AakashGfude I see these are currently all done through option flags which is a great short term solution. We can discuss migrating to a second builder for the `jupytersite` today and look at what will be the best long term solution if we want an extension that builds notebooks (as a priority) and then can build websites (in addition). 

I agree with @jstac ``make local`` should be default `make jupyter` behaviour. It produces a collection of jupyter notebooks with images that are referenced locally (i.e. files in the _static folder). This allows easy use of local notebooks. @AakashGfude let's run through all the options we have in the extension and catalog each against the commands above so we can document the behaviour of each command clearly.

**Comment by mmcky** [comment]
@jstac can you leave this with me to merge this afternoon. I would like to review the diff line by line with @AakashGfude to double check all the settings are as we intend them to be re: integrating `make local` and undoing some of those settings for `make website` etc.

**Comment by jlperla** [comment]
All sounds great, thanks guys!

**Comment by arnavs** [comment]
Looks good to me. Will keep an eye out for a PR to the `-jl` repo.

**Comment by mmcky** [comment]
Thanks @AakashGfude for these updates. 

We will need to update `sphinxcontrib-jupyter` and the `jupyter_images_urlpath` so that this option affects the `download` notebooks only so that figures in that collection of notebooks are served from the website. This will restore functionality of `local` and `preview` viewing when directory structures change etc.

- [ ] await fix in `sphinxcontrib-jupyter` before merging this branch.

**Comment by jstac** [comment]
Thanks guys.  Just to confirm, `make jupyter` will subsume `make local`, and, in particular, the default functionality of `make jupyter` should correspond to what previously was `make local`.

**Comment by mmcky** [comment]
- [ ] merge https://github.com/QuantEcon/quantecon.build.lectures/pull/117 once this is merged.

**Comment by mmcky** [comment]
@jstac that is correct -- we are reconfiguring `make jupyter` to be focused on local editing of `ipynb` notebooks with similar settings to `make local` in that it will encourage the use of `markdown` when writing notebooks.

**Comment by mmcky** [comment]
@AakashGfude is this ready to go? Let's review one last time today and run a verification build when you're in the lab today.

**Comment by mmcky** [comment]
This PR will rework the default settings in the `conf.py` file to enable `make jupyter` to focus on building local notebooks. The settings required for build the website will be enabled using override flags from the `cmd` line built into the `make website` command.

**Comment by mmcky** [comment]
@AakashGfude getting the following warnings

```
WARNING: The config value `jupyter_template_coverage_file_path' has type `bool', defaults to `str'.
WARNING: The config value `jupyter_images_urlpath' has type `NoneType', defaults to `bool'.
```

**Comment by mmcky** [comment]
this PR requires the following to be merged:

- [ ] https://github.com/QuantEcon/lecture-source-py/pull/449

**Pull request merged**
