### PR TITLE
linear_models_figure_to_code

### PR DESCRIPTION
**Pull request by shlff**
Good afternoon, @jstac . As we discussed in the [PR#893](https://github.com/QuantEcon/lecture-source-py/pull/893) and I showed to you yesterday, given your comments, I replaced all figures in the lecture [linear_models](https://python.quantecon.org/linear_models.html) with the code blocks that can generate those corresponding figures and deleted the sentence containing the link to the [old repo](https://github.com/QuantEcon/QuantEcon.lectures.code).

[Here](https://github.com/shlff/economics_with_python/blob/master/linear_models.ipynb) is the ``ipynb file`` compiled from the ``rst file`` with changes in this PR for the lecture.

Hi @jstac , I look forward to your comments. Thanks for @Harveyt47 and @sayaikegawa 's efforts in making these changes.

### CODE REVIEW

**Comment by Harveyt47** [comment]
Hi @shlff , Looks good to me.

**Comment by sayaikegawa** [comment]
Thanks @shlff , that looks good.

**Comment by jstac** [comment]
Hi @shlff , the code is well written and this is a good PR.  I appreciate you giving me a link to the generated notebook, to make it easier to review.

My only concern is the exercises: Exercises 1--4 ask the reader to replicate figures, but there's no challenge now because the code is already there.  

What I propose is this: 

1. Remove those exercises
2. Add a new exercises about forecasting geometric sums.  @Harveyt47 knows the basic idea.

Please let me know if you have any questions.

**Comment by shlff** [comment]
Good morning, @jstac . Thanks for your concern and excellent proposal, and this is also one thing we are concerned about. 

@Harveyt47 and I discussed the idea and its possibility of turning the [Forecasts of Geometric Sums](https://python.quantecon.org/linear_models.html#Forecasts-of-Geometric-Sums) subsection of this lecture into an exercise. We plan to read and work on the lecture [Geometric Series for Elementary Economics](https://python.quantecon.org/geom_series.html), which might help us come up with better exercise, like the strategy you adopted to design exercises in the first chapter, @jstac and @thomassargent30 .

Given your proposal and our discussion, I think we can improve this issue with 3 steps:
1. Remove ALL exercises in [Linear State Space Models](https://python.quantecon.org/linear_models.html),
2. Read and work on [Forecasts of Geometric Sums](https://python.quantecon.org/linear_models.html#Forecasts-of-Geometric-Sums) and add a basic exercise about geometric sums, based on examples in this lecture,
3. Turn [Forecasts of Geometric Sums](https://python.quantecon.org/linear_models.html#Forecasts-of-Geometric-Sums) subsection of [Geometric Series for Elementary Economics](https://python.quantecon.org/geom_series.html) into an exercise, based on the new exercise(s) in Step 2.

I will discuss this further with @Harveyt47 and @sayaikegawa next week to implement this plan.

**Comment by jstac** [comment]
Hi @shlff, it would be great if you could find a bit of time to work through this tonight.  I suggest that parts 2 and 3 of your proposal be combined.  That is, [this section](https://python.quantecon.org/linear_models.html#Forecasts-of-Geometric-Sums) becomes an exercise, up to where it says "Formulas".  Then the "Formulas" part becomes the solution.  

You might need to make some small adjustments to the wording.

(@mmcky, this is the last PR I want to get done.  The others are either yours or ones I'll close.)

**Comment by Harveyt47** [comment]
> Hi @shlff, it would be great if you could find a bit of time to work through this tonight. I suggest that parts 2 and 3 of your proposal be combined. That is, [this section](https://python.quantecon.org/linear_models.html#Forecasts-of-Geometric-Sums) becomes an exercise, up to where it says "Formulas". Then the "Formulas" part becomes the solution.
> 
> You might need to make some small adjustments to the wording.
> 
> (@mmcky, this is the last PR I want to get done. The others are either yours or ones I'll close.)

Hi @jstac , we are just putting the finishing touches on this now.

**Comment by shlff** [comment]
Thanks for collaborating with me, @Harveyt47 .

Hi @jstac , @Harveyt47 and I added a new exercise converted from the forecasting-geometric-sum part, and I compiled an ``ipynb`` file compiled from the ``rst`` file with these changes, please see [here](https://github.com/shlff/economics_with_python/blob/master/linear_models.ipynb).

I checked all its expressions, including maths. We are confident that these changes are correct, but would you mind having a look before you merge it?

**Comment by jstac** [comment]
Good work @shlff and @Harveyt47, many thanks for pushing to get this done.

**Pull request merged**
