### PR TITLE
[pandas] Update online data sources

### PR DESCRIPTION
**Pull request by mtllr**
Included code rewrite with pandas_datareader examples to acquire data from FRED, World Bank, etc...
Please note there is a rst reference to an external script for getting and munging the data from World Bank that I deleted because it has lost relevance. Not a sphinx pro so I don't know if I cleaned it properly.

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @mtllr!

I have three issues (and one reminder for myself):

1. The first new code block about the Italian data fails for me with error message `InvalidSchema: No connection adapters were found for '"http://www.statweb.provincia.tn.it/indicatoristrutturali/exp.aspx?fmt=json&idind=102&t=n"'`

2. For the data from the WB, would you mind to add `pip install --upgrade pandas_datareader`? 
 
3. The WB plot doesn't look right when I execute.  The text on the horizontal axis is a bit messed up and there's only one time series.  Screenshot attached.

Screenshot_2019-08-28_05-33-42

Note to self: The sentence starting "Supposing you have this..." needs to be adjusted.

**Comment by mtllr** [comment]
Hi @jstac ,

in order of appearance:

1) My first guess is an error from the requests library because the string is quoted twice, once with ' then with ". The get method was expecting an  'http' and not a '"' character. It is a little cryptic and I will try to reproduce anyway.

2) Sorry, I am not accustomed to this dev flow. Do you mean add this somewhere in the import statements at the beginning of the pandas.rst? like line 59?

3) Haha, I might have avoided that but my pycharm editor is not compatible with the sphinx configuration. What editor do you use?

**Comment by jstac** [comment]
Thanks @mtllr 

The basic principle is that everything should run in a Jupyter notebook for someone with an up to date Anaconda installation.

Here's an example of a lecture with a pip install at the start: https://lectures.quantecon.org/py/optgrowth.html

I appreciate this.

**Comment by mtllr** [comment]
Hi @jstac ,

I have fixed the file as per your comments.

Comments on the diff:
- Don't worry for the changes in the README.md, I just changed a typo: Anacoda -> Anaconda. The extra diffs are my editor removing spaces at the end of the line.
- .gitignore: added an ignore line for a venv/ folder so a user can virtualize his work.
- pandas.rst: fixed pip install, requests issue, plotting issue and sphinx indexing.

**Comment by jstac** [comment]
Thanks @mtllr, nice job.

**Comment by mtllr** [comment]
You are welcome John.

QuantEcon is a great project and I am glad I could bring a modest contribution.

Keeping my eyes on the list of open issues to see if I can contribute some more. 

Have a good day,

Martin

On 1 Oct 2019, at 03:10, John Stachurski <notifications@github.com> wrote:

Thanks @mtllr <https://github.com/mtllr>, nice job.

**Pull request merged**
